# Site settings
title: LINUS FREDRIKSSON  
email: linfredriksson@gmail.com
url: https://linfredriksson.github.io/
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: linus fredriksson

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://https://linfredriksson.github.io/
  - title: github
    url: https://https://linfredriksson.github.io/
  - title: vimeo
    url: https://https://linfredriksson.github.io/
  - title: sketchfab
    url: https://https://linfredriksson.github.io/
  - title: thingiverse
    url: https://https://linfredriksson.github.io/
  - title: myminifactory
    url: https://https://linfredriksson.github.io/

# Build settings
markdown: kramdown
permalink: pretty
