# Site settings
title: LINUS FREDRIKSSON  
email: contact@linusfredriksson.com
url: https://linfredriksson.github.io/
description: "Software developer, tinkerer, metal fan, gym rat, swede, human?"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#a53145'

# Footer settings
footer: linus fredriksson

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/linusfredriksson
  - title: github
    url: https://www.github.com/linfredriksson
  - title: vimeo
    url: https://www.vimeo.com/linusfredriksson
  - title: sketchfab
    url: https://sketchfab.com/linfredriksson/models
  - title: thingiverse
    url: https://www.thingiverse.com/linfredriksson
  - title: myminifactory
    url: https://www.myminifactory.com/users/linusfredriksson

# Build settings
markdown: kramdown
permalink: pretty
